"""create_initial_postgis_schema

Revision ID: 800cb9f75154
Revises: None
Create Date: 2026-09-02 23:33:41.604484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '800cb9f75154'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('name_hi', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('standard_mandi_unit', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en')
    )
    op.create_table('impact_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('farmer_net_gain_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('buyer_savings_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_distance_saved_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wastage_prevented_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'BUYER', 'LOGISTICS_PROVIDER', 'OPERATOR_PROXY', name='user_role_enum'), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('buyer_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=256), nullable=False),
    sa.Column('buyer_type', sa.String(length=64), nullable=False),
    sa.Column('gstin', sa.String(length=32), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('demand_forecasts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('crop_type_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('forecast_status', sa.String(length=32), nullable=False),
    sa.Column('projected_demand_index', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('projected_deficit_tonnes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forecast_period_start', sa.Date(), nullable=False),
    sa.Column('forecast_period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('payout_upi_id', sa.String(length=128), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('logistics_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transporter_name', sa.String(length=128), nullable=False),
    sa.Column('vehicle_registration_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('operator_audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('operator_user_id', sa.UUID(), nullable=False),
    sa.Column('farmer_user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('crop_type_id', sa.UUID(), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('modal_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('arrival_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('crop_type_id', sa.UUID(), nullable=False),
    sa.Column('target_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acceptable_grades', sa.ARRAY(sa.Enum('GRADE_A', 'GRADE_B', 'PROCESSING_GRADE', name='quality_grade_enum')), nullable=False),
    sa.Column('delivery_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MATCHED', 'ORDER_CREATED', 'FULFILLED', 'EXPIRED', name='requirement_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_type_id', sa.UUID(), nullable=False),
    sa.Column('variety', sa.String(length=64), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quality_grade', sa.Enum('GRADE_A', 'GRADE_B', 'PROCESSING_GRADE', name='quality_grade_enum'), nullable=False),
    sa.Column('is_pre_harvest', sa.Boolean(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESERVED', 'HARVESTED', 'RESCUE_ACTIVE', 'SOLD', 'EXPIRED', 'CANCELLED', name='listing_status_enum'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('photos', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_urgent_rescue', sa.Boolean(), nullable=False),
    sa.Column('rescue_discount_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_types.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listings_composite_search', 'crop_listings', ['crop_type_id', 'status', 'is_pre_harvest', 'harvest_date'], unique=False)
    op.create_table('dynamic_clusters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('total_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_farm_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_freight_rupees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_delivered_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cluster_centroid', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'FULFILLED', 'DISSOLVED', name='cluster_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['buyer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('allocated_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agreed_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pickup_order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['dynamic_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_code', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('crop_type_id', sa.UUID(), nullable=False),
    sa.Column('total_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount_rupees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'ESCROW_LOCKED', 'PICKUP_SCHEDULED', 'IN_TRANSIT', 'DELIVERED', 'SETTLED', 'DISPUTED', 'CANCELLED', name='order_status_enum'), nullable=False),
    sa.Column('delivery_otp', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['dynamic_clusters.id'], ),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('dispute_reason', sa.String(length=64), nullable=False),
    sa.Column('withheld_amount_rupees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_farmer_allocations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('allocated_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('farmer_payout_amount_rupees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pickup_verification_otp', sa.String(length=8), nullable=False),
    sa.Column('is_picked_up', sa.Boolean(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_user_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Enum('ESCROW_LOCK', 'FARMER_PAYOUT', 'TRANSPORTER_FREIGHT', 'PLATFORM_FEE', 'REFUND', name='ledger_entry_type_enum'), nullable=False),
    sa.Column('amount_rupees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gateway_reference_id', sa.String(length=128), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating_score', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('transporter_id', sa.UUID(), nullable=True),
    sa.Column('total_distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('freight_payout_rupees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'PICKUP_IN_PROGRESS', 'LOADED', 'IN_TRANSIT', 'DELIVERED', name='shipment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transporter_id'], ['logistics_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('route_waypoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('waypoint_type', sa.String(length=16), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('stop_name', sa.String(length=128), nullable=False),
    sa.Column('payload_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_waypoints')
    op.drop_table('shipments')
    op.drop_table('reviews')
    op.drop_table('payments_ledger')
    op.drop_table('order_farmer_allocations')
    op.drop_table('disputes')
    op.drop_table('orders')
    op.drop_table('cluster_items')
    op.drop_table('dynamic_clusters')
    op.drop_index('idx_listings_composite_search', table_name='crop_listings')
    op.drop_table('crop_listings')
    op.drop_table('buyer_requirements')
    op.drop_table('price_observations')
    op.drop_table('operator_audit_logs')
    op.drop_table('logistics_profiles')
    op.drop_table('farmer_profiles')
    op.drop_table('demand_forecasts')
    op.drop_table('buyer_profiles')
    op.drop_table('users')
    op.drop_table('impact_metrics')
    op.drop_table('crop_types')
    # ### end Alembic commands ###
