import { useState } from 'react'
import { MarketplaceAiTrigger } from './MarketplaceAiTrigger'
import { MarketplaceInsightResult } from './MarketplaceInsightResult'
import { targetPriceOptions } from '../../services/bulkIntelligenceService'
import type { SupplyContribution } from '../../types'

export function TargetPriceAdvisor() {
  const [options, setOptions] = useState<Array<{ id: string; label: string; price: number; likelihood: number }> | null>(null)
  const values = () => {
    const fields = Array.from(document.querySelectorAll<HTMLInputElement>('input[type="number"]')); const quantity = Number(fields.find((field) => field.min === '100')?.value ?? 1000); const target = Number(fields.find((field) => field.min === '1')?.value ?? 32); const crop = document.querySelector<HTMLInputElement>('.rfq-form input:not([type])')?.value ?? 'Tomatoes'
    return { crop, quantity, target }
  }
  const setPrice = (price: number) => { const field = Array.from(document.querySelectorAll<HTMLInputElement>('input[type="number"]')).find((input) => input.min === '1'); if (!field) return; const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set; setter?.call(field, String(price)); field.dispatchEvent(new Event('input', { bubbles: true })); field.dispatchEvent(new Event('change', { bubbles: true })) }
  return <section className="bulk-price-advisor"><span className="eyebrow">Kisan Intelligence</span><h2>Target Price Advisor</h2><MarketplaceAiTrigger variant="inline" idleLabel="Compare target prices" idleHint="Set a target from current prototype price signals" stages={['Checking mandi intelligence', 'Reviewing active farmer asks', 'Considering requested quantity', 'Checking delivery timing', 'Preparing price options']} run={() => { const input = values(); const result = targetPriceOptions(input.crop, input.quantity, input.target); setOptions(result); return result }} renderResult={(result, reset) => <><MarketplaceInsightResult title="Target Price Advisor" recommendation="Choose a target rate that fits your procurement priority." confidence={78} factors={result.map((option) => ({ label: option.label, value: `₹${option.price}/kg · ${option.likelihood}% prototype match likelihood` }))} note="Likelihoods are deterministic prototype scores, not trained acceptance predictions." onClose={reset} footer="Uses current crop-intelligence anchors and the entered quantity; it does not guarantee fulfilment." /><div className="target-price-actions">{result.map((option) => <button className="btn btn-secondary" key={option.id} onClick={() => { setPrice(option.price); reset() }}>Use this price · ₹{option.price}/kg</button>)}</div></>} />{options && <p className="safe-note">Selected rate is written directly into the RFQ target-price field.</p>}</section>
}

export function ContributionMatchIntelligence({ contributions, total }: { contributions: SupplyContribution[]; total: number }) {
  const matched = contributions.reduce((sum, item) => sum + item.quantityKg, 0); const top = Math.max(0, ...contributions.map((item) => item.quantityKg)); const concentration = matched ? top / matched : 0; const fulfilment = total ? Math.min(100, Math.round(matched / total * 100)) : 0; const average = matched ? Math.round(contributions.reduce((sum, item) => sum + item.quantityKg * item.ratePerKg, 0) / matched) : 0
  return <div className="contribution-intelligence"><MarketplaceAiTrigger variant="inline" idleLabel="See match reasoning" idleHint="Review match strength and cluster risk" stages={['Weighting distance', 'Comparing price', 'Checking delivery timing', 'Reviewing reliability signal', 'Reviewing quality and concentration']} run={() => ({ title: 'Match Intelligence', recommendation: `${fulfilment}% of requested quantity is covered. ${concentration >= .65 ? 'High concentration risk: one supplier has a large share.' : 'Low procurement risk across the current cluster.'}`, confidence: Math.min(91, 60 + Math.round(fulfilment * .25) + contributions.length * 3), factors: [{ label: 'Distance · 30%', value: 'Backend weighted factor when a cluster is available' }, { label: 'Price · 25%', value: average ? `Average ₹${average}/kg` : 'Awaiting allocation' }, { label: 'Time · 20%', value: 'Delivery-window compatibility' }, { label: 'Reliability · 15%', value: 'Backend profile or deterministic prototype default' }, { label: 'Quality · 10%', value: 'Listing grade signal' }, { label: 'Cluster risk', value: concentration >= .65 ? 'Large single-supplier share' : `${contributions.length} supplier allocations` }] })} renderResult={(insight, reset) => <MarketplaceInsightResult {...insight} onClose={reset} footer="The five-factor weights are distance 30%, price 25%, time 20%, reliability 15% and quality 10%. Reliability and quality may be prototype defaults when no canonical cluster is available." />} /></div>
}
