export type PlaceholderId = 'produceDetails' | 'sell' | 'farmerOrders' | 'earnings' | 'insights' | 'consumerOrders' | 'saved' | 'howItWorks' | 'bulkSupply' | 'bulkRequests' | 'bulkOrders'

interface PlaceholderCopy { eyebrow: string; title: string; description: string; features: string[] }

const en: Record<PlaceholderId, PlaceholderCopy> = {
  produceDetails: { eyebrow: 'Produce management', title: 'Listing controls are being prepared', description: 'Editing quantities, pausing a listing, and updating harvest details will connect to the live marketplace in Phase 2.', features: ['Update available quantity', 'Pause or resume produce', 'Track buyer interest'] },
  sell: { eyebrow: 'Farmer selling flow', title: 'Your 60-second listing flow is next', description: 'The step-by-step sell experience will guide farmers through crop, quantity, harvest date, price, and optional photos—one simple question at a time.', features: ['Choose crop with large visual buttons', 'Set quantity and expected price', 'Preview fair-price guidance before publishing'] },
  farmerOrders: { eyebrow: 'Orders preview', title: 'Order management comes in Phase 2', description: 'The home dashboard uses realistic preview counts. Acceptance, pickup coordination, and order states will become interactive with the connected marketplace.', features: ['Review new buyer orders', 'Accept or decline clearly', 'See pickup time and payout'] },
  earnings: { eyebrow: 'Transparent payouts', title: 'Your earnings ledger is taking shape', description: 'Phase 2 will connect each completed order to a clear farmer payout and payment status.', features: ['Monthly earnings summary', 'Order-by-order payout details', 'No hidden deductions'] },
  insights: { eyebrow: 'Demand intelligence preview', title: 'Know what buyers need before you sell', description: 'Today’s dashboard price card is mocked. Regional demand signals and explainable recommendations arrive in a later intelligence phase.', features: ['Nearby crop demand', 'Indicative fair-price ranges', 'Simple Hindi recommendations'] },
  consumerOrders: { eyebrow: 'Orders & delivery', title: 'Checkout is coming in Phase 2', description: 'The marketplace is ready to explore today. Cart, checkout, payments, and live delivery states will connect in the next phase.', features: ['Secure checkout', 'Farm-to-door delivery status', 'Simple order history'] },
  saved: { eyebrow: 'Saved favourites', title: 'Keep your favourite farms close', description: 'Saved farms and produce collections will arrive alongside the connected marketplace in Phase 2.', features: ['Save produce for later', 'Follow trusted farms', 'See when fresh batches arrive'] },
  howItWorks: { eyebrow: 'The direct journey', title: 'Fewer handoffs. More value.', description: 'KisanLink coordinates farmers, transparent pricing, and shared pickup so produce travels a shorter, more accountable path.', features: ['Verified farm origin', 'Visible price breakdown', 'Coordinated farm pickup'] },
  bulkSupply: { eyebrow: 'Aggregated supply preview', title: 'Supply planning arrives in Phase 2', description: 'This supply card is built from deterministic nearby-farm data. Reservations and farmer aggregation are intentionally not active yet.', features: ['Review contributing farmers', 'Compare landed pricing', 'Reserve the required quantity'] },
  bulkRequests: { eyebrow: 'Reverse marketplace', title: 'Post procurement requirements next', description: 'Soon FreshKart can publish crop, grade, quantity, delivery window, and ceiling price for nearby farmers to fulfil.', features: ['Define quantity and quality', 'Receive nearby supply plans', 'Compare transparent landed costs'] },
  bulkOrders: { eyebrow: 'Procurement orders', title: 'One place for every supply commitment', description: 'Order lifecycle, delivery sign-off, and procurement history are intentionally reserved for the connected Phase 2 experience.', features: ['Track accepted supply', 'Review delivery windows', 'Confirm received quantities'] },
}

const hi: Record<PlaceholderId, PlaceholderCopy> = {
  produceDetails: { eyebrow: 'फसल संभालें', title: 'फसल सूची के विकल्प तैयार हो रहे हैं', description: 'मात्रा बदलना, फसल रोकना और कटाई की जानकारी अपडेट करना Phase 2 में लाइव बाज़ार से जुड़ेगा।', features: ['उपलब्ध मात्रा बदलें', 'फसल रोकें या फिर शुरू करें', 'खरीदारों की रुचि देखें'] },
  sell: { eyebrow: 'फसल बेचने का आसान तरीका', title: '60 सेकंड में फसल डालने की सुविधा आगे आएगी', description: 'आसान चरणों में फसल, मात्रा, कटाई की तारीख, कीमत और चाहें तो फोटो पूछी जाएगी—एक बार में एक सरल सवाल।', features: ['बड़े चित्र वाले बटन से फसल चुनें', 'मात्रा और अपेक्षित कीमत डालें', 'बेचने से पहले सही कीमत की सलाह देखें'] },
  farmerOrders: { eyebrow: 'ऑर्डर की झलक', title: 'ऑर्डर संभालने की सुविधा Phase 2 में आएगी', description: 'मुख्य पृष्ठ पर अभी डेमो गिनती है। जुड़े बाज़ार में ऑर्डर स्वीकार करना, पिकअप तय करना और स्थिति देखना संभव होगा।', features: ['नए खरीदार ऑर्डर देखें', 'साफ़ तरीके से स्वीकार या मना करें', 'पिकअप समय और भुगतान देखें'] },
  earnings: { eyebrow: 'साफ़ भुगतान', title: 'आपकी कमाई का हिसाब तैयार हो रहा है', description: 'Phase 2 में हर पूरा ऑर्डर साफ़ किसान भुगतान और उसकी स्थिति से जुड़ेगा।', features: ['महीने की कमाई का सार', 'हर ऑर्डर का भुगतान', 'कोई छिपी कटौती नहीं'] },
  insights: { eyebrow: 'मांग की जानकारी की झलक', title: 'बेचने से पहले जानें खरीदारों को क्या चाहिए', description: 'आज के मुख्य पृष्ठ की कीमत डेमो है। आगे आपके क्षेत्र की मांग और आसान सलाह मिलेगी।', features: ['पास की फसल मांग', 'सही कीमत की अनुमानित सीमा', 'आसान हिन्दी सलाह'] },
  consumerOrders: { eyebrow: 'ऑर्डर और डिलीवरी', title: 'चेकआउट Phase 2 में आएगा', description: 'आज आप बाज़ार देख सकते हैं। अगले चरण में कार्ट, चेकआउट, भुगतान और लाइव डिलीवरी जुड़ेंगे।', features: ['सुरक्षित चेकआउट', 'खेत से घर तक डिलीवरी स्थिति', 'आसान ऑर्डर इतिहास'] },
  saved: { eyebrow: 'सहेजी पसंद', title: 'अपने पसंदीदा खेत पास रखें', description: 'सहेजे खेत और फसल संग्रह Phase 2 में जुड़े बाज़ार के साथ आएंगे।', features: ['फसल बाद के लिए सहेजें', 'भरोसेमंद खेतों को फॉलो करें', 'नई ताज़ी खेप आने पर देखें'] },
  howItWorks: { eyebrow: 'सीधा सफ़र', title: 'कम बिचौलिए। अधिक लाभ।', description: 'KisanLink किसानों, साफ़ कीमत और साझा पिकअप को जोड़ता है ताकि फसल कम हाथों से होकर आए।', features: ['सत्यापित खेत की पहचान', 'कीमत का साफ़ बंटवारा', 'मिलकर खेत से पिकअप'] },
  bulkSupply: { eyebrow: 'जुड़ी सप्लाई की झलक', title: 'सप्लाई योजना Phase 2 में आएगी', description: 'यह सप्लाई कार्ड पास के खेतों के तय डेमो डेटा से बना है। बुकिंग और किसान समूह अभी सक्रिय नहीं हैं।', features: ['योगदान देने वाले किसान देखें', 'कुल पहुंची कीमत की तुलना करें', 'ज़रूरी मात्रा बुक करें'] },
  bulkRequests: { eyebrow: 'खरीद की ज़रूरत डालें', title: 'अगले चरण में खरीद ज़रूरत पोस्ट करें', description: 'जल्द FreshKart फसल, ग्रेड, मात्रा, डिलीवरी समय और अधिकतम कीमत डाल सकेगा जिसे पास के किसान पूरा कर सकें।', features: ['मात्रा और गुणवत्ता तय करें', 'पास की सप्लाई योजनाएं पाएं', 'कुल साफ़ कीमत की तुलना करें'] },
  bulkOrders: { eyebrow: 'खरीद ऑर्डर', title: 'हर सप्लाई वादे की एक जगह', description: 'ऑर्डर की स्थिति, डिलीवरी पुष्टि और खरीद इतिहास Phase 2 में आएंगे।', features: ['स्वीकार सप्लाई ट्रैक करें', 'डिलीवरी समय देखें', 'मिली मात्रा की पुष्टि करें'] },
}

export const placeholderTranslations = { en, hi }
